In [1]:
import numpy as np

In [7]:
l=["nish",1,2,3,4]

In [8]:
type(l)

list

In [9]:
#convert list to array
np.array(l)

array(['nish', '1', '2', '3', '4'], dtype='<U11')

In [11]:
# data type is ndaray means n dimension array
type(np.array(l))

numpy.ndarray

In [19]:
# it is convert all integer number to floating point
b=np.array([3,4,5,6,3.0])

In [15]:
a = np.array([[1,2], [3,4]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [18]:
#pull out 4 from array
a[1][1]

4

In [20]:
b

array([3., 4., 5., 6., 3.])

In [21]:
#pull out 4 from b array
b[1]

4.0

In [25]:
#two bracket when pass ndimesion 2  (array within array) 2 dimesion array
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [26]:
#three bracket when pass ndimesion 3 (array within array) 3 dimesion array
np.array([1,2,3,4],ndmin=3)

array([[[1, 2, 3, 4]]])

In [27]:
#four bracket when pass ndimesion 4 (array within array) 4 dimesion array
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [29]:
a2=np.array([1,2,3,4],ndmin=4)

In [34]:
#pull put 2 from a2 array (a2 is 4 dimesion array)
a2[0][0][0][1]

2

In [35]:
a = np.array([[1,2], [3,4]])

In [36]:
# this is a two dimesion array (array within array) 2d
a

array([[1, 2],
       [3, 4]])

In [41]:
# np.array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [42]:
# np.asarray
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [43]:
# np.asanyarray
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [45]:
# matrix is 2d element np.mat (matrix is return by default minimum two dimesion)
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [46]:
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [47]:
#retunr matrix element default 2d
np.mat(a)

matrix([[1, 2, 3, 4, 5]])